name: Trigger Remote SBOM Workflow

on:
  release:
    types: [published]

jobs:
  call-remote-workflow:
    uses: eclipse-xfsc/dev-ops/.github/workflows/sbom-golang.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}